### ISSUE TITLE
dmgr_host not in options string in ::profile::dmgr

### ISSUE THREAD

**Issue by justindossey** [puppetlabs/puppetlabs-websphere#1]
In https://github.com/puppetlabs/puppetlabs-websphere/blob/master/manifests/profile/dmgr.pp#L51
You use `$::fqdn` as hostName argument, but I think it should be using the `dmgr_host` parameter (which defaults to `$::fqdn`) instead.

**Comment by mhaskel** [comment]
Thanks for the report @justindossey . That does look wrong. #3 should fix this.
