### ISSUE TITLE
How to call only ihs module?

### ISSUE THREAD

**Issue by deepumalladi** [puppetlabs/puppetlabs-websphere#12]
I am trying to only call ihs module in site.pp. I made changes in ihs/instance.pp accordingly.

my declaration in site.pp is as follows:
#class { 'websphere::ihs::instance': }

when i run agent -t --noop --debug

its throwing below error:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class websphere::ihs::instance at /etc/puppet/manifests/site.pp:

Can someone help:?

**Comment by joshbeard** [comment]
`websphere::ihs::instance` is a defined type, not a class.

Example usage is in the README: https://github.com/puppetlabs/puppetlabs-websphere#10-ihs

You'll also need to declare the base websphere class:  https://github.com/puppetlabs/puppetlabs-websphere#1-the-base-class

**Comment by deepumalladi** [comment]
Ok I tried it. Now my site.pp is

 node 'yyzcpa3002.ana.corp.aviva.com'{
   # include ibm_installation_manager
  websphere::ihs::instance { 'HTTPServer':
  target           => '/opt/IBM/HTTPServer',
  package          => 'com.ibm.websphere.IHS.v85_8.5.5000.20130514_1044',
  version          => '8.5.5000.20130514_1044',
  repository       => '/software_install/IHS/disk1/repository.config',
  install_options  => '-properties user.ihs.httpPort=8080',
  user             => 'root',
  group            => 'root',
  manage_user      => false,
  manage_group     => false,
  log_dir          => '/opt/log/websphere/httpserver',
  admin_username   => 'httpadmin',
  admin_password   => 'password',
}
}

Now i am facing below errors:

Error: Failed? Error: Could not execute posix command: Permission denied - /opt/IBM/InstallationManager/eclipse/tools install com.ibm.websphere.IHS.v85_8.5.5000.20130514_1044_8.5.5000.20130514_1044 -repositories /software_install/IHS/disk1/repository.config -installationDirectory /opt/IBM/HTTPServer -acceptLicense -properties user.ihs.httpPort=8080

Error: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/Websphere::Package[IHS HTTPServer]/Ibm_pkg[IHS HTTPServer]/ensure: change from absent to present failed: Failed? Error: Could not execute posix command: Permission denied - /opt/IBM/InstallationManager/eclipse/tools install com.ibm.websphere.IHS.v85_8.5.5000.20130514_1044_8.5.5000.20130514_1044 -repositories /software_install/IHS/disk1/repository.config -installationDirectory /opt/IBM/HTTPServer -acceptLicense -properties user.ihs.httpPort=8080

Notice: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/Websphere::Package[IHS HTTPServer]/Websphere::Ownership[pkg_IHS HTTPServer]/Exec[Ownership_pkg_IHS HTTPServer]: Dependency Ibm_pkg[IHS HTTPServer] has failures: true
Warning: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/Websphere::Package[IHS HTTPServer]/Websphere::Ownership[pkg_IHS HTTPServer]/Exec[Ownership_pkg_IHS HTTPServer]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/File[ihs_adminconf_HTTPServer]: Dependency Ibm_pkg[IHS HTTPServer] has failures: true
Warning: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/File[ihs_adminconf_HTTPServer]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/File[/opt/web]: Dependency Ibm_pkg[IHS HTTPServer] has failures: true
Warning: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/File[/opt/web]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/Service[ihs_admin_HTTPServer]: Dependency Ibm_pkg[IHS HTTPServer] has failures: true
Warning: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/Service[ihs_admin_HTTPServer]: Skipping because of failed dependencies
Notice: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/File[/opt/log/websphere/httpserver]: Dependency Ibm_pkg[IHS HTTPServer] has failures: true
Warning: /Stage[main]/Main/Node[yyzcpa3002.ana.corp.aviva.com]/Websphere::Ihs::Instance[HTTPServer]/File[/opt/log/websphere/httpserver]: Skipping because of failed dependencies

my  base class 
class websphere (
  $base_dir     = '/opt/IBM',
  $user         = 'root',
  $group        = 'root',
  $user_home    = '/opt/IBM'
}

Can you please help me out to find the solution?

**Comment by deepumalladi** [comment]
my site.pp looks like this
 websphere::ihs::instance { 'HTTPServer':
  target           => '/opt/IBM/HTTPServer',
  package          => 'com.ibm.websphere.IHS.v85_8.5.5000.20130514_1044',
  version          => '8.5.5000.20130514_1044',
  repository       => '/software_install/IHS/repository.config',
  install_options  => '-properties user.ihs.httpPort=8080',
  user             => 'root',
  group            => 'root',
  manage_user      => false,
  manage_group     => false,
  log_dir          => '/opt/IBM/HTTPServer/logs',
  admin_username   => 'httpadmin',
  admin_password   => 'password',

and install_options in instance.pp is
 $install_options           = '/opt/IBM/InstallationManager/eclipse/tools/imcl install com.ibm.websphere.IHS.v85_8.5.5000.20130514_1044 -installationDirectory /opt/IBM/HTTPServer -repositories /software_install/IHS/repository.config -acceptLicense',

When i run agent, i am facing below error:
Error: Failed to apply catalog: Could not find dependency File[ihs_adminconf_HTTPServer] for Service[ihs_admin_HTTPServer] at /etc/puppet/modules/websphere/manifests/ihs/instance.pp:155

Can you please help me to resolve the issue?
