### ISSUE TITLE
Which repo?

### ISSUE THREAD

**Issue by crayfishx** [puppetlabs/puppetlabs-websphere#5]
There appears to be a joshbeard/puppet-websphere and a puppetlabs/puppetlabs-websphere module that appear to be identical but one is not a fork of the other - which repo should be used for contributions?

Thanks
Craig

**Comment by joshbeard** [comment]
Hey Craig,

My repo under the "joshbeard" namespace was moved here, so that should redirect to THIS repo.  This is the main repo.

**Comment by hunner** [comment]
Thanks josh!
